version: 2
updates:
  # JavaScript/Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "PageCloudv1/frontend-team"
    assignees:
      - "rootkit-original"
    labels:
      - "dependencies"
      - "javascript"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 3
    reviewers:
      - "PageCloudv1/backend-team"
    assignees:
      - "rootkit-original"
    labels:
      - "dependencies"
      - "python"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
      
  # Go dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 3
    reviewers:
      - "PageCloudv1/backend-team"
    assignees:
      - "rootkit-original"
    labels:
      - "dependencies"
      - "golang"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
      
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 2
    reviewers:
      - "PageCloudv1/devops"
      - "PageCloudv1/security-team"
    assignees:
      - "rootkit-original"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"
      
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 2
    reviewers:
      - "PageCloudv1/devops"
    assignees:
      - "rootkit-original"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"