name: default-template
description: "Template padrão para novos repositórios PageCloudv1"

files:
  - .github/workflows/ci.yml
  - .github/CODEOWNERS
  - .github/dependabot.yml
  - .github/ISSUE_TEMPLATE/
  - .github/PULL_REQUEST_TEMPLATE.md
  - .gitignore
  - README.md
  - SECURITY.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - LICENSE
  - package.json
  - pyproject.toml

settings:
  has_issues: true
  has_projects: true
  has_wiki: true
  has_discussions: true
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
  default_branch: main
  
features:
  - github_actions
  - advanced_security
  - secret_scanning
  - dependency_graph
  - automated_security_fixes
  - vulnerability_alerts
  
labels:
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"
  - name: "invalid"
    color: "e4e669"
    description: "This doesn't seem right"
  - name: "question"
    color: "d876e3"
    description: "Further information is requested"
  - name: "wontfix"
    color: "ffffff"
    description: "This will not be worked on"